spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:noteapp
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
     url: jdbc:postgresql://localhost:5438/fastapi-ca2  # PostgreSQL 데이터베이스 URL
     username: admin                        # PostgreSQL 사용자 이름
     password: oracle                        # PostgreSQL 비밀번호
     driver-class-name: org.postgresql.Driver       # PostgreSQL 드라이버 클래스
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6636422..
            client-secret: GOCSP..
            scope:
              - email
              - profile


jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=
  secret_key: study-springboot
  token-validity-in-hours: 6


springdoc:
#  packages-to-scan: com.noteapp.controller
  packages-to-scan: com.noteapp.adapter.in.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  cache:
    disabled: true